### ISSUE TITLE
pRuntime should exit when the secure enclave crashed 

### ISSUE THREAD

**Issue by krhougs** [Phala-Network/phala-blockchain#1107]
![IMG_1499](https://user-images.githubusercontent.com/1382065/211206950-2451177b-8563-49e7-8383-6953be302665.png)

The whole app should exit when the enclave panicked and crashed instead of staying in a unrecoverable state where the HTTP RPC keeps returning 500.

**Comment by kvinwang** [comment]
The advantage of having the app exit when the enclave crashes is that the pruntime can silently restart, but at the same time, the PRB will not be able to know what happened with the pruntime because there will be no opportunity for the pruntime to send the response of the RPC which causing the crash.

If the app does not crash, the PRB will be able to record that the enclave has crashed and restart the pruntime through a kick.

Note: if the sgx driver crashes, even restarting the pruntime may not recover the pruntime.

Another reason to have the app exit together is to keep consistent with pruntime 2.0. Pruntime 2.0 no longer separates the app and enclave parts and naturally exits altogether after a crash.

**Comment by krhougs** [comment]
So for this case pRuntime v0 should catch the enclave crashed error and return an another state code like [this](https://http.cat/418) other than a confusing 500 Internal Server Error so pRB can acknowledge that pRuntime is crashed and stop meaningless retrying.

**Comment by kvinwang** [comment]
> So for this case pRuntime v0 should catch the enclave crashed error and return an another state code like [this](https://http.cat/418) other than a confusing 500 Internal Server Error so pRB can acknowledge that pRuntime is crashed and stop meaningless retrying.

This is indeed an `Internal Server Error`. It is not appropriate to use a different HTTP status code for it, because the HTTP code isn't designed for that. We should have defined an app-level error code, but unfortunately, we did not design one at the beginning and Rust's ecosystem does not support error-code style programming.

I think we should do the following:

 - Allow pruntime v0 to exit when the enclave crashes, to keep it consistent with pruntime v2.
 - Add an app-level error code, even if it may not work well with Rust's error handling. We can try to add some basic distinctions between important errors.
 
However, both are low priority. The priority is to fix the bugs that are causing the crash.

PRB can currently parse the error string to distinguish some errors for the already published pruntime.

**Comment by jasl** [comment]
For workaround I agree with `Allow pruntime v0 to exit when the enclave crashes, to keep it consistent with pruntime v2.`

with container auto restart, I believe it will improve our situation much better, and easy to made

**Comment by kvinwang** [comment]
Closing since it was resolved
