### ISSUE TITLE
`actix-web` has link error with rustup toolchain nightly-2022-04-01

### ISSUE THREAD

**Issue by Soptq** [Phala-Network/phala-blockchain#723]
https://github.com/actix/actix-web/issues/2671

Suggesting to upgrade to actix-web v4.

**Comment by kvinwang** [comment]
Turns out it is a bit complicate.
Currently, we can not upgrade it due to the zstd [issue](https://github.com/gyscos/zstd-rs/issues/147).
This the require sequences of upstream to fixes:

- [ ] zstd [fixes](https://github.com/gyscos/zstd-rs/pull/148) the root issue itself. But since the zstd is a FFI binding crate, **I don't think the fix could be as simple as the PR do**. FFI binding versioning always pain.
- [ ] substrate upgrade zstd to a fixed version.
- [ ] actix-web upgrace zstd to a fixed version.

# Alternative
If the upstream doesn't fix the issue in time, our project even can not compile when we upgrade substrate if substrate and actix-web still DO NOT depend on a common version of zstd.
Consider replace `actix-web` with `Rocket` or other framework.
